# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operand_one', models.IntegerField()),
                ('operand_two', models.IntegerField()),
                ('operation', models.CharField(max_length=1)),
                ('answer', models.IntegerField()),
            ],
        ),
    ]
